version: "2"
services:
  backendapp:
    build: server/
    ports:
      - 8080:8080
  frontendapp:
    build: frontend/
    ports:
      - 80:3000
    volumes:
      - './front-end:/usr/src/app'
      - '/usr/src/app/node_modules'
    depends_on:
      - backendapp